# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vighnesh/work/test1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vighnesh/work/test1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vighnesh/work/test1/CMakeFiles /home/vighnesh/work/test1//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vighnesh/work/test1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test1

# Build rule for target.
test1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test1
.PHONY : test1

# fast build rule for target.
test1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/build
.PHONY : test1/fast

src/Main.o: src/Main.cpp.o
.PHONY : src/Main.o

# target to build an object file
src/Main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/src/Main.cpp.o
.PHONY : src/Main.cpp.o

src/Main.i: src/Main.cpp.i
.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s
.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

src/Networking/BindingSocket.o: src/Networking/BindingSocket.cpp.o
.PHONY : src/Networking/BindingSocket.o

# target to build an object file
src/Networking/BindingSocket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/src/Networking/BindingSocket.cpp.o
.PHONY : src/Networking/BindingSocket.cpp.o

src/Networking/BindingSocket.i: src/Networking/BindingSocket.cpp.i
.PHONY : src/Networking/BindingSocket.i

# target to preprocess a source file
src/Networking/BindingSocket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/src/Networking/BindingSocket.cpp.i
.PHONY : src/Networking/BindingSocket.cpp.i

src/Networking/BindingSocket.s: src/Networking/BindingSocket.cpp.s
.PHONY : src/Networking/BindingSocket.s

# target to generate assembly for a file
src/Networking/BindingSocket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/src/Networking/BindingSocket.cpp.s
.PHONY : src/Networking/BindingSocket.cpp.s

src/Networking/ListeningSocket.o: src/Networking/ListeningSocket.cpp.o
.PHONY : src/Networking/ListeningSocket.o

# target to build an object file
src/Networking/ListeningSocket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/src/Networking/ListeningSocket.cpp.o
.PHONY : src/Networking/ListeningSocket.cpp.o

src/Networking/ListeningSocket.i: src/Networking/ListeningSocket.cpp.i
.PHONY : src/Networking/ListeningSocket.i

# target to preprocess a source file
src/Networking/ListeningSocket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/src/Networking/ListeningSocket.cpp.i
.PHONY : src/Networking/ListeningSocket.cpp.i

src/Networking/ListeningSocket.s: src/Networking/ListeningSocket.cpp.s
.PHONY : src/Networking/ListeningSocket.s

# target to generate assembly for a file
src/Networking/ListeningSocket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/src/Networking/ListeningSocket.cpp.s
.PHONY : src/Networking/ListeningSocket.cpp.s

src/Networking/SimpleSocket.o: src/Networking/SimpleSocket.cpp.o
.PHONY : src/Networking/SimpleSocket.o

# target to build an object file
src/Networking/SimpleSocket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/src/Networking/SimpleSocket.cpp.o
.PHONY : src/Networking/SimpleSocket.cpp.o

src/Networking/SimpleSocket.i: src/Networking/SimpleSocket.cpp.i
.PHONY : src/Networking/SimpleSocket.i

# target to preprocess a source file
src/Networking/SimpleSocket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/src/Networking/SimpleSocket.cpp.i
.PHONY : src/Networking/SimpleSocket.cpp.i

src/Networking/SimpleSocket.s: src/Networking/SimpleSocket.cpp.s
.PHONY : src/Networking/SimpleSocket.s

# target to generate assembly for a file
src/Networking/SimpleSocket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/src/Networking/SimpleSocket.cpp.s
.PHONY : src/Networking/SimpleSocket.cpp.s

src/Servers/SimpleServer.o: src/Servers/SimpleServer.cpp.o
.PHONY : src/Servers/SimpleServer.o

# target to build an object file
src/Servers/SimpleServer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/src/Servers/SimpleServer.cpp.o
.PHONY : src/Servers/SimpleServer.cpp.o

src/Servers/SimpleServer.i: src/Servers/SimpleServer.cpp.i
.PHONY : src/Servers/SimpleServer.i

# target to preprocess a source file
src/Servers/SimpleServer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/src/Servers/SimpleServer.cpp.i
.PHONY : src/Servers/SimpleServer.cpp.i

src/Servers/SimpleServer.s: src/Servers/SimpleServer.cpp.s
.PHONY : src/Servers/SimpleServer.s

# target to generate assembly for a file
src/Servers/SimpleServer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/src/Servers/SimpleServer.cpp.s
.PHONY : src/Servers/SimpleServer.cpp.s

src/Servers/TestServer.o: src/Servers/TestServer.cpp.o
.PHONY : src/Servers/TestServer.o

# target to build an object file
src/Servers/TestServer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/src/Servers/TestServer.cpp.o
.PHONY : src/Servers/TestServer.cpp.o

src/Servers/TestServer.i: src/Servers/TestServer.cpp.i
.PHONY : src/Servers/TestServer.i

# target to preprocess a source file
src/Servers/TestServer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/src/Servers/TestServer.cpp.i
.PHONY : src/Servers/TestServer.cpp.i

src/Servers/TestServer.s: src/Servers/TestServer.cpp.s
.PHONY : src/Servers/TestServer.s

# target to generate assembly for a file
src/Servers/TestServer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/src/Servers/TestServer.cpp.s
.PHONY : src/Servers/TestServer.cpp.s

src/t1.o: src/t1.cpp.o
.PHONY : src/t1.o

# target to build an object file
src/t1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/src/t1.cpp.o
.PHONY : src/t1.cpp.o

src/t1.i: src/t1.cpp.i
.PHONY : src/t1.i

# target to preprocess a source file
src/t1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/src/t1.cpp.i
.PHONY : src/t1.cpp.i

src/t1.s: src/t1.cpp.s
.PHONY : src/t1.s

# target to generate assembly for a file
src/t1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/src/t1.cpp.s
.PHONY : src/t1.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test1"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
	@echo "... src/Networking/BindingSocket.o"
	@echo "... src/Networking/BindingSocket.i"
	@echo "... src/Networking/BindingSocket.s"
	@echo "... src/Networking/ListeningSocket.o"
	@echo "... src/Networking/ListeningSocket.i"
	@echo "... src/Networking/ListeningSocket.s"
	@echo "... src/Networking/SimpleSocket.o"
	@echo "... src/Networking/SimpleSocket.i"
	@echo "... src/Networking/SimpleSocket.s"
	@echo "... src/Servers/SimpleServer.o"
	@echo "... src/Servers/SimpleServer.i"
	@echo "... src/Servers/SimpleServer.s"
	@echo "... src/Servers/TestServer.o"
	@echo "... src/Servers/TestServer.i"
	@echo "... src/Servers/TestServer.s"
	@echo "... src/t1.o"
	@echo "... src/t1.i"
	@echo "... src/t1.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

